### PR TITLE
Implement cryptocurrency enums

### LINKED ISSUE #169: Implement cryptocurrency enums
Let's support the following coins first: BAND, BTC, ETH.

### LINKED ISSUE #170: Update cryptocompare to take cryptocurrency enum

### LINKED ISSUE #171: Update coingecko to take cryptocurrency enum

### PR DESCRIPTION
**Pull request by taobun**
fixed #169 
fixed #170 
fixed #171 

- Implement cryptocurrency enum (`Coins`)
- Update how to use new parameters in `coingecko` and `cryptocompare`
- Test in our chain successfully

Endpoint now look like this
```
{
  "height": "0",
  "result": {
    "scriptInfo": {
      "name": "Crypto price (enum version)",
      "codeHash": "5Ot8kaUSYCpi9ePcW1a9GYM5E6/evUBaIqZxa26z03Q=",
      "params": [
        {
          "name": "symbol",
          "type": "coins::Coins"
        }
      ],
      "dataSources": [
        {
          "name": "coin_gecko",
          "type": "f32"
        },
        {
          "name": "crypto_compare",
          "type": "f32"
        }
      ],
      "creator": "band15d4apf20449ajvwycq8ruaypt7v6d345n9fpt9"
    },
    "codeHash": "E4EB7C91A512602A62F5E3DC5B56BD19833913AFDEBD405A22A6716B6EB3D374",
    "params": {
      "symbol": "BTC"
    },
    "targetBlock": "173",
    "requester": "band15d4apf20449ajvwycq8ruaypt7v6d345n9fpt9",
    "txhash": "C8350FD30D14242669DADED6270979961A2F63DC2F894713FB1E003B59C271B0",
    "requestedAtHeight": "169",
    "requestedAtTime": "2020-01-20T07:26:29Z",
    "reports": [
      {
        "reporter": "bandvaloper1zpmsn2vg2zcrx4jlg49t2f2y2cwjykr6jnmyxv",
        "txhash": "70AD190E175D1DA6A29BB9BA32790BB917BF0AFC6CCB798178416840929174E3",
        "reportedAtHeight": "170",
        "reportedAtTime": "2020-01-20T07:26:35Z",
        "value": {
          "coin_gecko": 8680.6,
          "crypto_compare": 8679.28
        }
      },
      {
        "reporter": "bandvaloper1r8u4m0wefrdyp7sdde7drtrt94qczggkq8r3xa",
        "txhash": "6A5CE9D81936A80B7414E9851AB0A5539A41884018DFF35EF224BA3D0DE696AC",
        "reportedAtHeight": "170",
        "reportedAtTime": "2020-01-20T07:26:35Z",
        "value": {
          "coin_gecko": 8680.6,
          "crypto_compare": 8679.31
        }
      },
      {
        "reporter": "bandvaloper1fwffdxysc5a0hu0falsq4lyneucj05cwryzfp0",
        "txhash": "0AF4C1A8FF0C4D9AAA2F45C93DE5D6B0CC04B3E3A9BC579F1130DB1B1EDEA5C1",
        "reportedAtHeight": "170",
        "reportedAtTime": "2020-01-20T07:26:35Z",
        "value": {
          "coin_gecko": 8680.6,
          "crypto_compare": 8679.28
        }
      },
      {
        "reporter": "bandvaloper13zmknvkq2sj920spz90g4r9zjan8g58423y76e",
        "txhash": "3E670B7D852D047D5FDE24926EBC700853857739487ED4F6F521F91CBFF62D60",
        "reportedAtHeight": "170",
        "reportedAtTime": "2020-01-20T07:26:35Z",
        "value": {
          "coin_gecko": 8680.6,
          "crypto_compare": 8679.31
        }
      }
    ],
    "result": "AAAAAAANPpo="
  }
}
```

### CODE REVIEW

**Review by sorawit — DISMISSED** [review]
Looks good.

**Review by prin-r — DISMISSED** [review]

**Comment by smiled0g** [comment]
lgtm

**Review by smiled0g — APPROVED** [review]
lgtm

**Review by prin-r — APPROVED** [review]
looks great

**Review by evilpeach — APPROVED** [review]

**Pull request merged**
